export const ROOM_TYPE = "ROOM_TYPE";
export const GUEST_NUMBER = "GUEST_NUMBER";
export const PRICE_RANGE = "PRICE_RANGE";
export const MIN_ROOM_SIZE = "MIN_ROOM_SIZE";

export const FILTER_DATA = "FILTER_DATA";
export const HALF_BOARD_CHECKBOX = "HALF_BOARD_CHECKBOX";
export const FULL_BOARD_CHECKBOX = "FULL_BOARD_CHECKBOX";
